---
title: "ESM244 HW2"
author: "Sara Orofino"
date: "2/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load packages
library(tidyverse)

# read in data 
fish <- read_csv("fish_catch.csv")
cetacean <- read_csv("captive_cetacean.csv")
```

#{.tabset}
##Task 1

###Data Visualization - Cetaceans in Captivity

```{r wrangle1, message=FAlSE, warning=FALSE}

# look at captive births over the years by location  

acq_data <- cetacean %>% 
    filter(originLocation != "NA",
           originLocation != "Unknown",
           birthYear !="NA",
           acquisition =="Born") %>% 
  select(species, birthYear, originLocation) %>% 
  group_by(originLocation, birthYear) %>% 
  count()

# Lots of locations... consider grouping the locations into states?
# Need a list of the states for the locations:
# California - Marineland of the Pacific, SeaWorld San Diego, Six Flags Discovery Kingdom, Dolphin Experience  
# Illinois - Brookfield Zoo, Shedd Aquarium  
# Florida - Discovery Cove, Dolphin Connection, Dolphin Research Center, Dolphin Plus Bayside, Dolphin Plus Oceanside, Gulf Wolrd Marine Park, Gulfarium, Marineland Florida, Miami Sequarium, Theater of the Sea
# International - Dolphin Quest Bermuda, Marineland Antibes, Marineland Canada, Sealand of the Pacific 
# Hawaii - Dolphin Quest Hawaii, Kahala Hilton Oahu, Sea Life Park 
# Georgia - Georgia Aquarium
# Minnesota - Minnesota Zoo
# Nevada - Mirage Dolphin Habitat
# Indiana - Indianapolis Zoo 
# Maryland - National Aquarium
# Massachusetts - New England Aquarium 
# Ohio - SeaWorld of Ohio, SeaWorld Aurora
# Texas - SeaWorld San Antonio 
# US Navy - U.S. Navy and U.S. Navy MMP 

# Regions (According to US Census Bureau):
# West - Marineland of the Pacific, SeaWorld San Diego, Six Flags Discovery Kingdom, Dolphin Experience, Dolphin Quest Hawaii, Kahala Hilton Oahu, Sea Life Park, 
## West includes Hawaii, California, Nevada
# South - Discovery Cove, Dolphin Connection, Dolphin Research Center, Dolphin Plus Bayside, Dolphin Plus Oceanside, Gulf Wolrd Marine Park, Gulfarium, Marineland Florida, Miami Sequarium, Theater of the Sea, SeaWorld San Antonio, Georgia Aquarium,  
## South includes Florida, Texas, Georgia, 
# Midwest - Minnesota Zoo, Indianapolis Zoo, Brookfield Zoo, Shedd Aquarium, SeaWorld of Ohio, SeaWorld Aurora 
## Midwest includes Minnesota, Indiana, Ohio and Illinois 
# Northeast - National Aquarium, New England Aquarium 
## Northeast - Maryland and Massachusetts 
# Military - U.S. Navy and U.S. Navy MMP 
# International - Dolphin Quest Bermuda, Marineland Antibes, Marineland Canada, Sealand of the Pacific
```


```{r}
#stacked column graph 

ggplot(acq_data, aes(x = birthYear, y = n , group = originLocation, fill = originLocation))+
  geom_bar(stat = "identity")
```


##Task 2 

###Parameter Estimation - Wild Fish Catch 



##Task 3 

###Boostrapped Confidence Interval for Proportions 



##Task 4

###R-Studio Conference Talks 
